### ISSUE TITLE
[Suggestion] Rename 'master' to 'main'

### ISSUE THREAD

**Issue by szymski** [Bartekkur1/janpa-js#2]
Some of you might have noticed, that due to recent events in US, most software developers decided to get rid of names like blacklist/whitelist or master/slave from their projects. I think we should do the same for JanpaJS. Master branch naming is just racist and should not take place in our repo. Please change it to 'main'.

**Comment by Bartekkur1** [comment]
Hi @szymski, first of all I don't understand what you mean by "US"? you mean that fictitious country "USA" that supposedly lies over Atlantic Ocean? I do not want to be rude, I'll just attach below image of a real earth globe (do your homework). 
- shorturl.at/m0157

Regarding the "master" branch name, thats default name so if you do not like it you should go ask Linus why he did it that way.
